Refactor the new version of the core
EasyMicroservices/Support-Microservice pull request #3
Opened 2023-11-21 15:53 UTC by Elyas-Amini

## Description

### Related issue(s)

### Checklist:

- [ ] It refers to an [Issue](https://github.com/EasyMicroservices/FileManager/issues).
- [ ] It fixes a bug.
- [ ] It's a new feature (non-breaking change which adds functionality)
- [ ] It's a breaking (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] CHANGELOG is updated.
- [ ] Related language label is selected.

2023-11-21 17:40 UTC, MahdiyarGHD approved these changes

2023-11-21 17:47 UTC, Ali-YousefiTelori requested changes

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Database/Database/Contexts/SupportContext.cs
> +        public DbSet<TicketSupportTimeHistoryEntity> TicketSupportTimeHistoryHistories { get; set; }
```suggestion
        public DbSet<TicketSupportTimeHistoryEntity> TicketSupportTimeHistories { get; set; }
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Database/EasyMicroservices.SupportsMicroservice.Database.csproj
> +	  <PackageReference Include="EasyMicroservices.Cores.AspCoreApi" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Database/EasyMicroservices.SupportsMicroservice.Database.csproj
> +	  <PackageReference Include="EasyMicroservices.Cores.Relational.EntityFrameworkCore" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Database/EasyMicroservices.SupportsMicroservice.Database.csproj
> +	  <PackageReference Include="EasyMicroservices.Cores.AspEntityFrameworkCoreApi" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Domain/EasyMicroservices.SupportsMicroservice.Domain.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.AspCoreApi" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Domain/EasyMicroservices.SupportsMicroservice.Domain.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.Database" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Domain/EasyMicroservices.SupportsMicroservice.Domain.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.Relational.EntityFrameworkCore" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Logics/EasyMicroservices.SupportsMicroservice.Logics.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.AspCoreApi" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Logics/EasyMicroservices.SupportsMicroservice.Logics.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.AspEntityFrameworkCoreApi" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Logics/EasyMicroservices.SupportsMicroservice.Logics.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.Relational.EntityFrameworkCore" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Logics/EasyMicroservices.SupportsMicroservice.Logics.csproj
> +    <PackageReference Include="EasyMicroservices.Mapper.CompileTimeMapper" Version="0.0.0.6" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Services/EasyMicroservices.SupportsMicroservice.Services.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.AspCoreApi" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Services/EasyMicroservices.SupportsMicroservice.Services.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.AspEntityFrameworkCoreApi" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Services/EasyMicroservices.SupportsMicroservice.Services.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.Relational.EntityFrameworkCore" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.StartUp/DatabaseBuilder.cs
> +            //optionsBuilder.UseInMemoryDatabase("CommentDatabase");
```suggestion
            //optionsBuilder.UseInMemoryDatabase("SupportDatabase");
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.StartUp/EasyMicroservices.SupportsMicroservice.StartUp.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.AspCoreApi" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.StartUp/EasyMicroservices.SupportsMicroservice.StartUp.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.AspEntityFrameworkCoreApi" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.StartUp/EasyMicroservices.SupportsMicroservice.StartUp.csproj
> +    <PackageReference Include="EasyMicroservices.Cores.Relational.EntityFrameworkCore" Version="0.0.0.49" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.StartUp/EasyMicroservices.SupportsMicroservice.StartUp.csproj
> +    <PackageReference Include="EasyMicroservices.WhiteLabelsMicroservice.Clients" Version="0.0.0.9" />
```suggestion
```

2023-11-21 17:47 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.WebApi/Controllers/DepartmentController.cs
> +        private readonly IContractLogic<DepartmentEntity, CreateDepartmentRequestContract, UpdateDepartmentRequestContract, DepartmentContract, long> _contractlogic;
You don't need to use contractlogic property. use unitofwork inside of your methods

2023-11-22 11:03 UTC, mahdidelzendeh72 approved these changes
thanks

2023-11-22 17:12 UTC, Ali-YousefiTelori requested changes

2023-11-22 17:12 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Domain/EasyMicroservices.SupportsMicroservice.Domain.csproj
> +    <Folder Include="Contracts  Requests\Filters\" />
its wrong path

2023-11-22 18:46 UTC, Elyas-Amini commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Domain/EasyMicroservices.SupportsMicroservice.Domain.csproj
> +    <Folder Include="Contracts  Requests\Filters\" />
It was fixed

2023-11-23 09:38 UTC, Ali-YousefiTelori approved these changes

2023-11-23 09:39 UTC, merged