Add TicketDiscussion
EasyMicroservices/Support-Microservice pull request #4
Opened 2023-11-27 15:44 UTC by Elyas-Amini

## Description

### Related issue(s)

### Checklist:

- [ ] It refers to an [Issue](https://github.com/EasyMicroservices/FileManager/issues).
- [ ] It fixes a bug.
- [x It's a new feature (non-breaking change which adds functionality)
- [ ] It's a breaking (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] CHANGELOG is updated.
- [ ] Related language label is selected.

2023-11-27 16:42 UTC, MahdiyarGHD approved these changes

2023-11-27 16:46 UTC, Ali-YousefiTelori requested changes
Please remove controller logic

2023-11-28 14:02 UTC, AmirmohammadNemati approved these changes

2023-11-28 15:25 UTC, Ali-YousefiTelori requested changes

2023-11-28 15:25 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Database/Database/Contexts/SupportContext.cs
> +                model.HasIndex(bc => bc.TicketId).IsUnique();
Please remove IsUnique.

2023-11-28 15:25 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.SupportsMicroservice.Database/Database/Contexts/SupportContext.cs
> +                model.HasIndex(bc => bc.TicketId).IsUnique();
Please remove IsUnique.

2023-11-28 15:49 UTC, AmirmohammadNemati approved these changes

2023-11-28 15:53 UTC, Ali-YousefiTelori approved these changes

2023-11-28 15:54 UTC, merged

2023-12-05 14:28 UTC, mahdidelzendeh72 reviewed
thanks